# Generated by Django 3.2.7 on 2021-11-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='примечание')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('year', models.IntegerField(verbose_name='год производства')),
                ('runtime', models.CharField(max_length=100, verbose_name='длительность')),
                ('genre', models.CharField(max_length=100, verbose_name='жанр фильма')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='постер')),
                ('imdb_id', models.CharField(default=1, max_length=100, verbose_name='imdb id')),
                ('released', models.CharField(max_length=100, verbose_name='премьера в мире')),
                ('plot', models.TextField(default=1, verbose_name='сюжет')),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='рейтинг')),
                ('imdb_votes', models.CharField(max_length=50, verbose_name='количество голосов')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='CartMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='отзыв')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name=' отзыв добавлен')),
                ('cart_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='movie.cart', verbose_name='ссылка на Cart')),
                ('movie_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie.movie', verbose_name='ссылка на Movie')),
            ],
        ),
    ]
