# Generated by Django 3.2.7 on 2021-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=255, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=255, verbose_name='жанр фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=255, verbose_name='imdb id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=255, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_votes',
            field=models.CharField(max_length=255, verbose_name='количество голосов'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(verbose_name='сюжет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.CharField(max_length=255, verbose_name='премьера в мире'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=255, verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
