# Generated by Django 3.2.7 on 2021-11-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.IntegerField(blank=True, null=True, verbose_name='постер'),
        ),
    ]
